groups:
  - name: enthropic-trading-alerts
    rules:
      # High error rate
      - alert: HighErrorRate
        expr: |
          sum(rate(http_requests_total{status=~"5.."}[5m])) 
          / sum(rate(http_requests_total[5m])) > 0.05
        for: 2m
        labels:
          severity: critical
        annotations:
          summary: "High error rate detected"
          description: "Error rate is {{ $value | humanizePercentage }} over the last 5 minutes"

      # Order processing latency
      - alert: HighOrderLatency
        expr: histogram_quantile(0.99, rate(order_processing_duration_seconds_bucket[5m])) > 0.1
        for: 5m
        labels:
          severity: warning
        annotations:
          summary: "High order processing latency"
          description: "P99 order latency is {{ $value }}s"

      # Circuit breaker open
      - alert: CircuitBreakerOpen
        expr: circuit_breaker_state == 1
        for: 1m
        labels:
          severity: critical
        annotations:
          summary: "Circuit breaker is open"
          description: "Circuit breaker {{ $labels.name }} is open"

      # Service down
      - alert: ServiceDown
        expr: up == 0
        for: 1m
        labels:
          severity: critical
        annotations:
          summary: "Service is down"
          description: "{{ $labels.job }} has been down for more than 1 minute"

      # High memory usage
      - alert: HighMemoryUsage
        expr: process_resident_memory_bytes / 1024 / 1024 > 512
        for: 5m
        labels:
          severity: warning
        annotations:
          summary: "High memory usage"
          description: "{{ $labels.job }} is using {{ $value }}MB of memory"

      # Database connection pool exhausted
      - alert: DBPoolExhausted
        expr: db_pool_available_connections == 0
        for: 1m
        labels:
          severity: critical
        annotations:
          summary: "Database connection pool exhausted"
          description: "No available database connections for {{ $labels.service }}"

      # NATS subscription lag
      - alert: NATSHighLag
        expr: nats_consumer_pending_messages > 1000
        for: 2m
        labels:
          severity: warning
        annotations:
          summary: "NATS consumer lag is high"
          description: "{{ $labels.consumer }} has {{ $value }} pending messages"

      # Position calculation errors
      - alert: PositionCalculationErrors
        expr: rate(position_calculation_errors_total[5m]) > 0
        for: 1m
        labels:
          severity: critical
        annotations:
          summary: "Position calculation errors detected"
          description: "{{ $value }} position errors per second"
